
CC=/bin/gcc
SHELL=/bin/bash

CFLAGS=$(shell pkg-config --cflags webkit2gtk-4.1)
LIBS=$(shell pkg-config --libs webkit2gtk-4.1)

C_FILES=$(shell ls *.c)
H_FILES=$(shell ls *.h)

OUTPUT_FILE="gtk-kiwix"

CUSTOM_CFLAGS= -I./

gtk-kiwix: $(C_FILES) $(H_FILES)
	@echo "\nCompiling\n"
	$(CC) -o $(OUTPUT_FILE) $(C_FILES) $(CFLAGS) $(CUSTOM_CFLAGS) $(LIBS)
	@echo -e "\n\n\t\t\tDONE!!!\n\n"
